name: my_portfolio
description: "my portfolio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

